const actionTypes = {

  //GetId
  GET_USER_ID_START: "GET_USER_ID_START",
  GET_USER_ID_SUCCESS: "GET_USER_ID_SUCCESS",
  GET_USER_ID_ERROR: "GET_USER_ID_ERROR",

  //Update
  UPDATE_USER_START: "UPDATE_USER_START",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_ERROR: "UPDATE_USER_ERROR",

  //Create
  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",

  //Clear
  CLEAR_USER_START: "CLEAR_USER_START",
};

export default actionTypes;
