const actionTypes = {
  //GetAll
  GET_MOVIES_START: "GET_MOVIES_START",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_ERROR: "GET_MOVIES_ERROR",
  //GetId
  GET_MOVIE_ID_START: "GET_MOVIE_ID_START",
  GET_MOVIE_ID_SUCCESS: "GET_MOVIE_ID_SUCCESS",
  GET_MOVIE_ID_ERROR: "GET_MOVIE_ID_ERROR",
  //GetRandom
  GET_MOVIE_RANDOM_START: "GET_MOVIE_RANDOM_START",
  GET_MOVIE_RANDOM_SUCCESS: "GET_MOVIE_RANDOM_SUCCESS",
  GET_MOVIE_RANDOM_ERROR: "GET_MOVIE_RANDOM_ERROR",
};

export default actionTypes;
